# ------------------------------------------------------------------------------
# Pull base image
FROM debian:bullseye
LABEL author="Brett Kuskie <fullaxx@gmail.com>"

# ------------------------------------------------------------------------------
# Set environment variables
ENV DEBIAN_FRONTEND="noninteractive"

# ------------------------------------------------------------------------------
# Create a docker image suitable for development
# libpcap0.8-dbg is not available in jammy
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      bash-completion \
      build-essential \
      ca-certificates \
      cmake \
      curl \
      doxygen \
      file \
      git \
      less \
      libgdk-pixbuf-xlib-2.0-dev \
      libgtk2.0-dev \
      libgtk-3-dev \
      meson \
      ninja-build \
      python3-minimal && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Install claude-code
COPY install_nodejs_repo.sh /scripts/
RUN /scripts/install_nodejs_repo.sh 18 && \
    apt-get install -y nodejs && \
    npm install -g @anthropic-ai/claude-code && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* /tmp/*

# ------------------------------------------------------------------------------
# Define default command
CMD ["/bin/bash"]
